cronjob:
  schedule: "@daily"
  priorityClassName: ""
  ttlSecondsAfterFinished: 7776000

# "ssmsend" or "gratia"
outputFormat: ssmsend


# If true, /cvmfs/grid.cern.ch/etc/grid-security/certificates/ will be mounted as a hostPath volume.
# If false, you will need to set up an alternative way of providing the ca-policy-* packages and CRLs in the ssmsend container.
gridSecurityHostPath: true

# If pspName is defined, this PSP will be used. If gridSecurityHostPath, use of a (read-only) /cvmfs hostPath is required.
# Other than that no special privileges are required so a default PSP should be sufficient.
pspName: ""

# UID and GID for the pod service user
user:
  uid: 10000
  gid: 10000

# Size of the data volume in which to store intermediate APEL records. outputFormat "gratia"
# outputs individual records rather than summaries, and may require a larger data volume size.
dataVolumeSize: 1000M

processor:
  image_repository: "hub.opensciencegrid.org/osgpreview/kapel-processor"
  # Optionally overwrite container version. Default is chart appVersion.
  image_tag: ""
  image_pull_policy: "IfNotPresent"
  resources:
    # very generous estimate: approx 10 KiB memory per job record
    limits:
      cpu: "1"
      memory: "2000Mi"
    requests:
      cpu: "0.5"
      memory: "500Mi"

  config:
    # The name of the site being reported.
    siteName: "EXAMPLE-T2"
    # Uniquely identifying name for the cluster.
    submitHost: "k8s.example.org:6443/namespace"
    # Namespace of the pods for which Kuantifier will collect and report metrics.
    namespace: "harvester"
    # VO of Jobs
    voName: "atlas"
    # Infrastructure Type
    infrastructureType: "grid"
    # Output path for intermediate APEL records
    outputPath: /srv/kapel

  # Prometheus configuration and authentication
  prometheus:
    # URL of the Prometheus server. Default value works within cluster for default bitnami/kube-prometheus Helm release.
    server: http://kube-prometheus-prometheus.kube-prometheus:9090
    # If the Prometheus server is authorized, a secret containing the authentication header for the server
    auth:
      secret: null
      key: null

  # Configuration for the prometheus query used to generate reports
  query:
    # "Auto" to report on the most recent month of data, "gap" to report on a specific time interval
    mode: "auto"
    # Exit with an error if the query does not complete within the timeout
    timeout: "1800s"
    # Start date for gap reporting
    startDate: null
    # End date for gap reporting
    endDate: null


ssmsend:
  resources:
    limits:
      cpu: "0.5"
      memory: "500Mi"
    requests:
      cpu: "0.1"
      memory: "50Mi"
  # Whether to actually send data. Use false for testing.
  enabled: true
  # Location of ssmsend container. Feel free to instead build your own using the provided Containerfile.
  image_repository: "git.computecanada.ca:4567/rptaylor/misc/ssmsend"
  # Optionally overwrite container version. Default is chart appVersion.
  image_tag: ""
  host: "msg.argo.grnet.gr"
  # base64-encoded strings of the X509 public cert and private key for APEL publisher.
  # Using a base64 encoded string with no line breaks avoids issues of indentation and double YAML encoding if Ansible is used for Helm.
  x509cert: aW5zZXJ0IGJhc2U2NC1lbmNvZGVkIHN0cmluZyBvZiB0aGUgWDUwOSBwdWJsaWMgY2VydCBmb3IgQVBFTCBwdWJsaXNoZXIK
  x509key: aW5zZXJ0IGJhc2U2NC1lbmNvZGVkIHN0cmluZyBvZiB0aGUgWDUwOSBwcml2YXRlIGtleSBmb3IgQVBFTCBwdWJsaXNoZXIK

  # Environment variables for the processor that determine ssmsend-specific behavior. 
  config:
    # The value to use for normalizing by CPU performance.
    benchmarkValue: "15.0"
    # Number of nodes the report summarizes over.
    nodeCount: "0"
    # Number of processors the report summarizes over.
    processors: "0"

gratia:
  resources:
    limits:
      cpu: "0.5"
      memory: "500Mi"
    requests:
      cpu: "0.1"
      memory: "50Mi"
  # Location of gratia output container.
  image_repository: "hub.opensciencegrid.org/osgpreview/kapel-gratia-output"
  # Optionally overwrite container version. Default is chart appVersion.
  image_tag: ""
  # Config options for Gratia. At present, only gratiaConfigPath can be specified,
  # And points to the default Gratia config file.
  config:
    gratiaConfigPath: "/etc/gratia/kubernetes/ProbeConfig"


nameOverride: ""
fullnameOverride: ""
