services:
  kapel-processor:
    image: hub.opensciencegrid.org/osgpreview/kuantifier-processor:1.0.3-rc3
    build:
      context: .
      network: host
  runtime-exporter:
    image: hub.opensciencegrid.org/iris-hep/kuantifier-runtime-exporter:1.0.0
    build:
      context: runtime_exporter
