{{ if eq .Values.outputFormat "gratia" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gratia-output-config
  labels:
    {{- include "kapel.labels" . | nindent 4 }}
data:
{{ if kindIs "string" .Values.gratia.config }}
# Deprecated: Specify the whole ConfigMap as a multiline string
{{ .Values.processor.config | indent 2 }}
{{ else }}
  GRATIA_CONFIG_PATH: {{ .Values.gratia.config.gratiaConfigPath }}
{{ end }}
{{ end }}
