{{ if eq .Values.outputFormat "gratia" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gratia-output-config
  labels:
    {{- include "kapel.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.gratia.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{ end }}
