{{ if eq .Values.output_format "gratia" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gratia-output-config
  labels:
    {{- include "kapel.labels" . | nindent 4 }}
data:
{{ .Values.gratia.config | indent 2 }}
{{ end }}
