apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-processor-config
  labels:
    {{- include "kapel.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.processor.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
